### ISSUE TITLE
Why print ("We can't use this buffer but render it due to the API limit, " + outBuffer)

### ISSUE THREAD

**Issue by xjsXjtu** [taehwandev/MediaCodecExample#1]
Hi, 

I am new to Android and MediaCodec. Thanks for your example code, I can build and run successfully on my Nexus 5 now. 

I have a question. In AudioDecoderThread.java line 205, why do you print this info? It souds like something wrong, but actually it's working fine. 
  ByteBuffer outBuffer = outputBuffers[outIndex];
  Log.v("DecodeActivity", "We can't use this buffer but render it due to the API limit, " + outBuffer);

Thanks a lot in advance:)

**Comment by taehwandev** [comment]
Hello.
The answer late.
Meaning that it can not be written to the output line to SurfaceView.
thank.
