### ISSUE TITLE
How to get a CSD - 0

### ISSUE THREAD

**Issue by cwenlu** [taehwandev/MediaCodecExample#5]
Hi.What is the specified the principle of CSD - 0

ByteBuffer csd = ByteBuffer.allocate(2);
		csd.put((byte) ((audioProfile << 3) | (sampleIndex >> 1)));
		csd.position(1);
		csd.put((byte) ((byte) ((sampleIndex << 7) & 0x80) | (channelConfig << 3)));
		csd.flip();
		format.setByteBuffer("csd-0", csd); // add csd-0
		
		for (int k = 0; k < csd.capacity(); ++k) {
			Log.e("TAG", "csd : " + csd.array()[k]);
		}

**Comment by taehwandev** [comment]
Hi cwenlu!

Csd-0 has audio profile information, sample index, and channel information.

The sample index is 

96000, 88200, 64000, 48000, 44100, 32000, 24000, 22050, 16000, 12000, 11025, 8000

It is as above. Each mapping number.

Reference : http://stackoverflow.com/questions/12942201/decoding-aac-using-mediacodec-api-on-android

**Comment by cwenlu** [comment]
ths
----- 原始邮件 -----
发件人：TaeHwan <notifications@github.com>
收件人：taehwandev/MediaCodecExample <MediaCodecExample@noreply.github.com>
抄送人：cwenlu <cwenlu@sina.cn>,  Author <author@noreply.github.com>
主题：Re: [taehwandev/MediaCodecExample] How to get a CSD - 0 (#5)
日期：2017年01月11日 11点42分

Hi cwenlu!
Csd-0 has audio profile information, sample index, and channel information.
The sample index is
96000, 88200, 64000, 48000, 44100, 32000, 24000, 22050, 16000, 12000, 11025, 8000
It is as above. Each mapping number.
Reference : http://stackoverflow.com/questions/12942201/decoding-aac-using-mediacodec-api-on-android

&mdash;

**Comment by cwenlu** [comment]
tks
