### ISSUE TITLE
Why makeAACCodecSpecificData() required?

### ISSUE THREAD

**Issue by ohtangza** [taehwandev/MediaCodecExample#6]
First of all, thanks for great example code.

I was looking into your code for decoding AAC files, and found that ```makeAACCodecSpecificData()``` was used to create ```MediaFormat``` object.

I am wondering that why it did not make use of the ```MediaFormat``` extracted from ```MediaExtractor```?

Thanks for your help in advance.

**Comment by taehwandev** [comment]
Sorry. I didn't manage the source.
makeAACCodecSpecificData is simply to process the data received from the server.

Enough to use MediaFormat and MediaExtractor.

**Comment by ohtangza** [comment]
Thanks for the reply. That helped me understand the code.
