### ISSUE TITLE
Audio Not Playing

### ISSUE THREAD

**Issue by rnandhakumar1995** [taehwandev/MediaCodecExample#8]
I have used your MediaCodec Example. The video is playing but the audio is not playing. How to play audio using the same MediaExtractor?

**Comment by taehwandev** [comment]
Hi. This example only supports`audio/mp4a-latm`.
You can use it when you want to create a custom header.

If you want to play other audio, you need to add MediaExtractor.

```
mExtractor = new MediaExtractor();
mExtractor.setDataSource(filePath);

// And find audio track.
String mime = format.getString(MediaFormat.KEY_MIME);
if (mime.startsWith("audio/")) {
	 mExtractor.selectTrack(i);
         // find audio and MediaCodec create from audio codec name
	 mDecoder = MediaCodec.createDecoderByType(mime);
	try {
		Log.d(TAG, "format : " + format);
		mDecoder.configure(format, null, null, 0);
	} catch (IllegalStateException e) {
		Log.e(TAG, "codec '" + mime + "' failed configuration. " + e);
		return false;
}
```

**Comment by rnandhakumar1995** [comment]
I want to play video and audio simultaneously. Is it possible? If yes can you please help me to do this?
